export type DosmeticObjData = {
  api_featured_image: string;
  brand: string;
  category: null;
  created_at: string;
  currency: null;
  description: string;
  id: number;
  image_link: string;
  name: string;
  price: string;
  price_sign: null;
  product_api_url: string;
  product_colors: [];
  product_link: string;
  product_type: string;
  rating: number;
  tag_list: [];
  updated_at: string;
  website_link: string;
};
export type DosmeticData = DosmeticObjData[];
